name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.4203
typography_spectrum: 1
title: 'ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#989187'
    - '#8ebed2'
    - '#7a4124'
    - '#feda46'
    - '#f2f0eb'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.3651780167128891
  rhythmicContrast: 0
purpose: []
