name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.11580555723048747
typography_spectrum: 0.99770488566719
title: 'CHALON ELECTRICITE - INDUSTRIEL & PARTICULIERS - 69'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.48933955980464816
  lightness: 0.968425482744351
  saturation: 0.6445719909388572
  rhythmicContrast: 0.7150966715998948
purpose: []
