name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.50454
typography_spectrum: 1
title: 'ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9efed'
    - '#dec0b6'
    - '#322d29'
    - '#918066'
    - '#020200'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
