name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 1
title: 'ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#919598'
    - '#d8d7dd'
    - '#674d40'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.3651780167128891
  rhythmicContrast: 0
purpose: []
