name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'CHALON ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6fbad9'
    - '#5f5f5f'
    - '#909090'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
