name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 0.9015
title: 'ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b4a5'
    - '#fefefe'
    - '#4f4f43'
    - '#1d1b26'
    - '#a0120a'
  brandStrength: 0.125
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
