name: CHALON ELECTRICITE
favicon: null
layout_spectrum: 0.38232
typography_spectrum: 1
title: 'ELECTRICITE GENERALE & INDUSTRIELLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373239'
    - '#f6f6f8'
    - '#88868b'
    - '#fb3c5d'
    - '#c0b9b1'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
